"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {MemberGate} from "@/features/auth/components/member-gate";
import {userSession,type Member} from "@/features/auth/user-session";
import {parseOwnProjects,projectWriteFailure,type OwnProjectPage} from "../api/member-projects";
function Projects({member}:{member:Member}) {
 const [page,setPage]=useState(0),[visibility,setVisibility]=useState(""),[data,setData]=useState<OwnProjectPage|null>(null),[error,setError]=useState(""),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let live=true;setData(null);setError("");void userSession.request(`/members/me/projects?page=${page}&size=20&sort=createdAt,desc${visibility?`&visibilityStatus=${visibility}`:""}`).then(value=>{if(live)setData(parseOwnProjects(value,page,member.id));}).catch(e=>{if(live)setError(projectWriteFailure(e));});return()=>{live=false;};},[page,visibility,attempt,member.id]);
 return <><div className="list-heading"><h1>내 프로젝트</h1><Link className="button" href="/projects/new">새 프로젝트 작성</Link></div><p>{member.nickname}님의 공개·비공개 프로젝트를 관리합니다.</p><label className="table-editor-field">공개 상태<select value={visibility} onChange={e=>{setVisibility(e.target.value);setPage(0);}}><option value="">전체</option><option value="PUBLIC">공개</option><option value="HIDDEN">비공개</option></select></label>{error?<section className="list-state"><p role="alert">{error}</p><button className="button" onClick={()=>setAttempt(n=>n+1)}>다시 불러오기</button></section>:!data?<p role="status">내 프로젝트를 불러오고 있어요.</p>:!data.content.length?<section className="list-state"><h2>{page>0?"이 페이지에는 프로젝트가 없어요.":visibility?"해당 상태의 프로젝트가 없어요.":"아직 작성한 프로젝트가 없어요."}</h2>{page>0&&<button className="button" onClick={()=>setPage(0)}>첫 페이지로</button>}</section>:<ul className="post-list">{data.content.map(project=><li className="post-card" key={project.id}><p>{project.visibilityStatus==="HIDDEN"?"비공개":"공개"} · {project.lifecycleStatus==="COMPLETED"?"완료":"진행 중"}{project.isBlocked?" · 관리자 차단":""}</p><h2><Link href={`/projects/${project.id}/edit`}>{project.name}</Link></h2>{project.summary&&<p>{project.summary}</p>}<ul className="tag-list" aria-label="기술 태그">{project.tags.map(tag=><li key={tag.id}>{tag.name}</li>)}</ul><Link className="button" href={`/projects/${project.id}/edit`}>수정하기</Link>{project.visibilityStatus==="PUBLIC"&&!project.isBlocked&&<Link className="button" href={`/projects/${project.id}`}>공개 프로젝트 보기</Link>}</li>)}</ul>}{data&&<nav className="pagination" aria-label="내 프로젝트 페이지"><button className="button" disabled={!data.hasPrevious} onClick={()=>setPage(n=>n-1)}>이전</button><span>{page+1} / {Math.max(1,data.totalPages)}</span><button className="button" disabled={!data.hasNext} onClick={()=>setPage(n=>n+1)}>다음</button></nav>}</>;
}
export function MyProjects(){return <MemberGate>{member=><Projects key={member.id} member={member}/>}</MemberGate>;}
